<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\LoginController:indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.m92v0v9']) ? $this->services['service_locator.m92v0v9'] : $this->load(__DIR__.'/getServiceLocator_M92v0v9Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\RegisterController:indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.rkcehev']) ? $this->services['service_locator.rkcehev'] : $this->load(__DIR__.'/getServiceLocator_RkcehevService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\LoginController::indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.m92v0v9']) ? $this->services['service_locator.m92v0v9'] : $this->load(__DIR__.'/getServiceLocator_M92v0v9Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\RegisterController::indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.rkcehev']) ? $this->services['service_locator.rkcehev'] : $this->load(__DIR__.'/getServiceLocator_RkcehevService.php')) && false ?: '_'};
})));
