<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHoj8qxm\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHoj8qxm/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHoj8qxm.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHoj8qxm\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHoj8qxm\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Hoj8qxm',
    'container.build_id' => '687cfdca',
    'container.build_time' => 1516209169,
));
