<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF23akzh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF23akzh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerF23akzh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerF23akzh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerF23akzh\appDevDebugProjectContainer(array(
    'container.build_hash' => 'F23akzh',
    'container.build_id' => 'dcfa5f2f',
    'container.build_time' => 1516631524,
));
