<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUhb2xcp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUhb2xcp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUhb2xcp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUhb2xcp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUhb2xcp\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Uhb2xcp',
    'container.build_id' => 'a055c77e',
    'container.build_time' => 1516793112,
));
